version: '3.8'

# Common configuration for all services
x-common-config: &common-config
  volumes:
    - ./data:/app/data
    - ./models:/app/models
    - ./results:/app/results
    - ./logs:/app/logs
  env_file:
    - .env
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  # Standard training service
  train:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libyan-sentiment-train
    <<: *common-config
    command: >
      sh -c "python -m scripts.train"

  # Hyperparameter optimization service
  optimize:
    build:
      context: .
      dockerfile: Dockerfile.optimize
    container_name: libyan-sentiment-optimize
    <<: *common-config
    # Uncomment and adjust resources as needed
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 8G
    command: >
      sh -c "python -m scripts.train --optimize"

  # SVD component tuning service
  tune-svd:
    build:
      context: .
      dockerfile: Dockerfile.optimize  # Uses same image as optimize
    container_name: libyan-sentiment-tune-svd
    <<: *common-config
    command: >
      sh -c "python -m scripts.train --tune-svd --min-components 10 --max-components 40 --step 5"

  # Jupyter notebook service for exploration (uncomment to use)
  # notebook:
  #   build: .
  #   container_name: libyan-sentiment-notebook
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
